In [1]:
import pandas as pd
import geopandas as gpd
import os

In [9]:
bfs = gpd.read_file('../data/shp_bfs/g1g23.shp', geometry='geometry', srs='epsg:2056')

In [10]:
bfs.head()

,GMDHISTID,GMDNR,GMDNAME,BZHISTID,BZNR,KTNR,GRNR,AREA_HA,E_MIN,E_MAX,N_MIN,N_MAX,E_CNTR,N_CNTR,Z_MIN,Z_MAX,Z_AVG,Z_MED,Z_CNTR,geometry
0,13256,1,Aeugst am Albis,10053,101,1,4,791,2678111,2681155,1234561,1238544,2679300,1235700,533,887,685,673,700,"POLYGON ((2678219.000 1235219.000, 2678439.000..."
1,11742,2,Affoltern am Albis,10053,101,1,4,1059,2673826,2678584,1235208,1239338,2676800,1236800,440,749,529,502,490,"POLYGON ((2678219.000 1235219.000, 2677940.000..."
2,11801,3,Bonstetten,10053,101,1,4,743,2675745,2679642,1238997,1243159,2677800,1241000,502,715,581,583,544,"POLYGON ((2675803.000 1241039.000, 2675748.000..."
3,11992,4,Hausen am Albis,10053,101,1,4,1360,2680394,2686463,1230185,1236411,2682900,1233100,524,915,673,653,610,"POLYGON ((2686324.000 1230388.000, 2686024.000..."
4,12249,5,Hedingen,10053,101,1,4,653,2674866,2678972,1238053,1241034,2676400,1239000,475,745,560,543,503,"POLYGON ((2675803.000 1241039.000, 2676538.000..."

In [11]:
keep_cols=['GMDNR', 'GMDNAME', 'BZNR', 'KTNR', 'geometry']

In [12]:
bfs = bfs.drop(columns=[col for col in bfs.columns if col not in keep_cols])

In [13]:
bfs

,GMDNR,GMDNAME,BZNR,KTNR,geometry
0,1,Aeugst am Albis,101,1,"POLYGON ((2678219.000 1235219.000, 2678439.000..."
1,2,Affoltern am Albis,101,1,"POLYGON ((2678219.000 1235219.000, 2677940.000..."
2,3,Bonstetten,101,1,"POLYGON ((2675803.000 1241039.000, 2675748.000..."
3,4,Hausen am Albis,101,1,"POLYGON ((2686324.000 1230388.000, 2686024.000..."
4,5,Hedingen,101,1,"POLYGON ((2675803.000 1241039.000, 2676538.000..."
...,...,...,...,...,...
2134,6807,Basse-Allaine,2603,26,"POLYGON ((2567009.521 1256868.290, 2566957.590..."
2135,6808,Clos du Doubs,2603,26,"POLYGON ((2569410.484 1246416.863, 2571130.000..."
2136,6809,Haute-Ajoie,2603,26,"POLYGON ((2559718.024 1248149.921, 2560200.000..."
2137,6810,La Baroche,2603,26,"POLYGON ((2584700.000 1251153.000, 2583718.000..."
2138,6811,Damphreux-Lugnez,2603,26,"POLYGON ((2576583.000 1258798.000, 2576638.000..."

In [85]:
results = pd.read_excel('../data/Results/Resultate.xlsx', sheet_name='data', header=0)

In [87]:
results = results.dropna(axis=0)

In [88]:
results.head(20)

,GMDNR,GMDNAME,Stimmberechtigte,Abgegebene Stimmen,Beteiligung in %,Gültige Stimmzettel,Ja,Nein,Ja in %
0,CH,Schweiz,5412449,2028856,37.48,2004253,1475000,529253,73.59
1,ZH,- Zürich,933499,367557,39.37,364358,262032,102326,71.92
2,000101,>> Bezirk Affoltern,35160,15539,44.2,15416,11061,4355,71.75
3,0001,......Aeugst am Albis,1402,664,47.36,663,481,182,72.55
4,0002,......Affoltern am Albis,7186,2880,40.08,2850,2079,771,72.95
5,0003,......Bonstetten,3656,1701,46.53,1691,1251,440,73.98
6,0004,......Hausen am Albis,2505,1145,45.71,1132,802,330,70.85
7,0005,......Hedingen,2515,1183,47.04,1178,876,302,74.36
8,0006,......Kappel am Albis,712,281,39.47,280,187,93,66.79
9,0007,......Knonau,1482,591,39.88,584,445,139,76.2
10,0008,......Maschwanden,461,197,42.73,196,133,63,67.86
11,0009,......Mettmenstetten,3378,1740,51.51,1725,1230,495,71.3
12,0010,......Obfelden,3472,1298,37.38,1287,902,385,70.09
13,0011,......Ottenbach,1851,850,45.92,844,604,240,71.56
14,0012,......Rifferswil,749,384,51.27,381,283,98,74.28
15,0013,......Stallikon,2370,1060,44.73,1053,671,382,63.72
16,0014,......Wettswil am Albis,3421,1565,45.75,1552,1117,435,71.97
17,000102,>> Bezirk Andelfingen,21952,10543,48.03,10419,6907,3512,66.29
18,0021,......Adlikon,501,260,51.9,256,130,126,50.78
19,0022,......Benken (ZH),602,271,45.02,267,145,122,54.31

In [72]:
df = results.loc[~results['GMDNAME'].str.startswith('>>')]
df = df.loc[~df['GMDNAME'].str.startswith('-')]

In [73]:
df

,GMDNR,GMDNAME,Stimmberechtigte,Abgegebene Stimmen,Beteiligung in %,Gültige Stimmzettel,Ja,Nein,Ja in %
0,CH,Schweiz,5412449,2028856,37.48,2004253,1475000,529253,73.59
3,0001,......Aeugst am Albis,1402,664,47.36,663,481,182,72.55
4,0002,......Affoltern am Albis,7186,2880,40.08,2850,2079,771,72.95
5,0003,......Bonstetten,3656,1701,46.53,1691,1251,440,73.98
6,0004,......Hausen am Albis,2505,1145,45.71,1132,802,330,70.85
...,...,...,...,...,...,...,...,...,...
2391,6807,......Basse-Allaine,951,264,27.76,260,191,69,73.46
2392,6808,......Clos du Doubs,1096,338,30.84,329,270,59,82.07
2393,6809,......Haute-Ajoie,983,318,32.35,314,224,90,71.34
2394,6810,......La Baroche,942,288,30.57,284,221,63,77.82
2396,9260,......JU-CH de l'étranger,...,...,...,...,...,...,...

In [74]:
df['GMDNAME'] = df['GMDNAME'].str[6:]

In [75]:
df = df.drop(index=0)

In [81]:
df['GMDNR'] = df['GMDNR'].astype(int)

In [84]:
df.to_csv('../export/results/results.csv', sep=';')

In [95]:
import pandas as pd
import geopandas as gpd
import os


def get_bfs():
    bfs = gpd.read_file('../data/shp_bfs/g1g23.shp',
                        geometry='geometry', srs='epsg:2056')
    keep_cols = ['GMDNR', 'GMDNAME', 'BZNR', 'KTNR', 'geometry']
    bfs = bfs.drop(
        columns=[col for col in bfs.columns if col not in keep_cols])

    return bfs


def get_results():
    results = pd.read_excel('../data/Results/Resultate.xlsx',
                            sheet_name='data', header=0)
    results = results.dropna(axis=0)

    df = results.loc[~results['GMDNAME'].str.startswith('>>')]
    df = df.loc[~df['GMDNAME'].str.startswith('-')]
    df['GMDNAME'] = df['GMDNAME'].str[6:]
    df = df.drop(index=0)
    df['GMDNR'] = df['GMDNR'].astype(int)

    return df


def export_df():
    get_bfs().to_csv('../export/results/bfs_data.csv', sep=';', index=False)
    get_results().to_csv('../export/results/results.csv', sep=';', index=False)

In [96]:
export_df()